import { createContext, useContext, useState } from "react";

const dictionary = {
    id: {
    home: "Beranda",
    catalog: "Katalog",
    cart: "Keranjang",
    addToCart: "Tambah ke keranjang",
    find: "Cari produk...",
    all: "Semua",
    emptyCart: "Keranjangmu masih kosong",
    total: "Total",
    checkoutBtn: "Lanjut ke checkout",
    checkoutTitle: "Checkout",
    fullName: "Nama lengkap",
    phone: "No. telepon",
    address: "Alamat pengiriman",
    orderSummary: "Ringkasan pesanan",
    placeOrder: "Buat pesanan",
    orderSuccess: "Pesanan berhasil dibuat",
    orderSuccessDesc: "Terima kasih! Pesananmu sedang diproses",
    backHome: "Kembali ke beranda",
    back: "Kembali",
    loading: "Memuat...",
    fail: "Gagal memuat produk. Coba refresh halaman atau coba beberapa saat lagi",
    again: "Coba lagi",
    notFound: "Produk tidak ditemukan",
    noMatch: "Tidak ada produk yang cocok",
    del: "Hapus",
    pref: "Preferensi",
    look: "Mode tampilan",
    choose: "Pilih tema yang nyaman, atau ikut sistem otomatis",
    language: "Bahasa",
    langPref: "Bahasa utama untuk navigasi, harga dan bantuan",
    metInput: "Metode Input",
    way: "Sesuaikan ukuran target dan navigasi fokus dengan caramu berinteraksi",
    ware: "Direkomendasikan - menyesuaikan perangkatmu",
    touch: "Target sentuh lebih besar",
    mouse: "Efek hover aktif",
    keyb: "Fokus ring selalu tampil",
    heroEyebrowLight: "Koleksi baru",
    heroTitleLight: "Hal kecil, suasana baru",
    heroSubLight: "Pilihan premium untuk hari yang lebih ceria",
    heroBtnLight: "Belanja sekarang",
    heroEyebrowDark: "Pilihan malam",
    heroTitleDark: "Cahaya tenang untuk ruang yang terasa milikmu",
    heroSubDark: "Kurasi nyaman untuk menjelajah kapan pun inspirasimu datang",
    heroBtnDark: "Belanja koleksi",
    favTitle: "Favorit minggu ini",
    seeAll: "Lihat semua",
    catHome: "Rumah",
    catStyle: "Gaya",
    catTech: "Tekno",
    catGift: "Hadiah",
    },
    en: {
    home: "Home",
    catalog: "Catalog",
    cart: "Cart",
    addToCart: "Add to cart",
    find: "Search products...",
    all: "All",
    emptyCart: "Your cart is empty",
    total: "Total",
    checkoutBtn: "Continue to checkout",
    checkoutTitle: "Checkout",
    fullName: "Full name",
    phone: "Phone number",
    address: "Shipping address",
    orderSummary: "Order summary",
    placeOrder: "Place order",
    orderSuccess: "Order placed successfully",
    orderSuccessDesc: "Thanks! Your order is being processed",
    backHome: "Back to home",
    back: "Back",
    loading: "Loading...",
    fail: "Failed to load the product. Try refreshing the page or try again later",
    again: "Try again",
    notFound: "Product not found",
    noMatch: "No matching products",
    del: "Delete",
    pref: "Preferences",
    look: "Display mode",
    choose: "Choose a cozy theme, or follow the automatic system",
    language: "Language",
    langPref: "Main language for navigation, price and help",
    metInput: "Input method",
    way: "Adjust the target size and focus navigation with the way you interact",
    ware: "Recommended - customise your device",
    touch: "Bigger touch target",
    mouse: "Active hover effect",
    keyb: "The ring's focus always appears",
    heroEyebrowLight: "New collection",
    heroTitleLight: "Small things, new mood",
    heroSubLight: "Premium picks for a brighter day",
    heroBtnLight: "Shop now",
    heroEyebrowDark: "Night picks",
    heroTitleDark: "Calm light for a space that feels like yours",
    heroSubDark: "A comfortable curation to explore whenever inspiration strikes",
    heroBtnDark: "Shop collection",
    favTitle: "Favorites this week",
    seeAll: "See all",
    catHome: "Home",
    catStyle: "Style",
    catTech: "Tech",
    catGift: "Gifts",
    },
}

const LanguageContext = createContext();

export function LanguageProvider ({children}) {
    const [lang, setLang] = useState("en");
    const t = (key) => dictionary[lang][key] || key;

    return (
        <LanguageContext.Provider value={{lang, setLang, t}}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    return useContext(LanguageContext);
}